# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 647bcb98d036b6d865072d3e831c92985969013510e36ce2de5e2da4e009b456b09b4a34152cd4ea7448415f5dd0b99dcd14213b9946363aa5a06805b302562a

test:
  secret_key_base: ca6f2c2f0f4ed9501c002ad0bb0702c45373f6361c1e01929da94e7838cad5b6dc9756cc46d92b933445381661b78fa4ee5cd9d981de26d503d8e2dd3e034616

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
